export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOG_OUT = "LOG_OUT";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const ADD_PROFILE = "ADD_PROFILE";

export const REMOVE_PROFILE = "REMOVE_PROFILE";

export const DB_USER_ID = "DB_USER_ID";

export const SUBMIT_BEER_DRINK = "SUBMIT_BEER_DRINK";

export const SUBMIT_COCKTAIL_DRINK = "SUBMIT_COCKTAIL_DRINK";

export const SUBMIT_WINE_DRINK = "SUBMIT_WINE_DRINK";

export const SUBMIT_LIQUOR_DRINK = "SUBMIT_LIQUOR_DRINK";

export const SUBMIT_BINGE_DRINK = "SUBMIT_BINGE_DRINK";

export const DRINK_ITEM = "DRINK_ITEM";

export const GET_ALL_DRINK_VALUES = "GET_ALL_DRINK_VALUES";

export const TOTAL_OF_ALL_DRINKS = " TOTAL_OF_ALL_DRINKS";

export const SET_LAST_DRINK_ITEM = "SET_LAST_DRINK_ITEM";

export const GUEST_LOGIN = "GUEST_LOGIN";