const liquorStore = {
    "1": ["beer","Drinking a brewski huh, welp enjoy!",1],
    "2": ["pint_beer","A good ole pint of beer",1.3],
    "3": ["tall_beer","Tall boy?, you must be thirsty!",2],
    "4": ["forty","A forty huh, welp, see ya later",3.3],
    "5": ["craft", "Craft beer, good choice.",1],
    "6": ["craft_pint","Nice refreshing pint of craft",1.3],
    "7": ["craft_tall","Tall craft to quench that thirst",2],
    "8": ["seltzer","Enjoy that seltzer my guy!",1],
    "9": ["tall_seltzer","Whoa, a tall seltzer!",2],
    "10": ["smirnoff_ice","Here in hopes you got iced. If not enjoy!",1],
    "11": ["six_percent","6% beer. You've upgraded from lite beer",1.3],
    "12": ["seven_percent","7% beer. Climbing up there",1.7],
    "13": ["eight_percent","8% beer. Hope it tastes good.",2.3],
    "14": ["nine_percent","9% beer. Might as well make it an even 10. Jk, enjoy!",2.7],
    "15": ["ten_percent","10%^. Whoa, we got a badass over here",3.5],
    "16": ["margarita", "Margarita.. that does sound good",1.5],
    "17": ["bloody_mary","Bloody Mary, Bloody Mary, Bloody Mary",1],
    "18": ["mimosa", "Mimosa, take advantage of the bottomless",1],
    "19": ["martini", "Feeling like James Bond with that Martini?",2],
    "20": ["mojito", "Moojjiittoo, rolls right off the tongue.",1],
    "21": ["gin_and_tonic", "gin and tonic",1],
    "22": ["moscow_mule","moscow mule",1],
    "23": ["paloma","paloma",1],
    "24": ["daiquiri","What are you some kinda girl or somethin? oh, you are, Enjoy!",1],
    "25": ["long_island","Careful long islands can sneak up on you.",2],
    "26": ["misc", "Cocktail wasn't on the menu huh. Better luck next drink.",1],
    "27": ["red_wine","Sit back relax, enjoy your glass of red wine",1.2],
    "28": ["white_wine","Sit back relax, enjoy your glass of white wine",1.2],
    "29": ["sangria","Sangria",1.2],
    "30": ["champagne","Poppin bottles are we? Don't forget to toast with your champagne.",1],
    "31": ["tequila_shot",'Alexa, play "The Champs"',1],
    "32": ["vodka_shot","Who still takes shots of vodkay?.. oh.",1],
    "33": ["whiskey_shot","Let me guess, a pickle back right?, no?, Well, enjoy.",1],
    "34": ["bourbon","bourbon",1],
    "35": ["scotch", "I love scotch, Scotchy, scotch, scotch. Here it goes down, down into my belly.",1],
    "36": ["brandy","brandy",1],
    "37": ["beer_bong","Was it good?, as soon it touhched the lips huh.",1],
    "38": ["shotgun","shotgun",1],
    "39": ["boilermaker","Whoa, how did that boilermaker taste..",2.5]
};

export default liquorStore;